/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/anakon_greek.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AnakonGreek {
  AnakonGreek._();

  static const _kFontFam = 'AnakonGreek';
  static const _kFontPkg = null;

  static const IconData greek_alpha = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greek_epsilon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greek_sigma = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greek_iota = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greek_upsilon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData o = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
